Update check-release.yaml

diff --git a/.github/workflows/check-release.yaml b/.github/workflows/check-release.yaml
--- a/.github/workflows/check-release.yaml
+++ b/.github/workflows/check-release.yaml
@@ -16,31 +16,31 @@ jobs:
       RCMDCHECK_ERROR_ON: error
       GITHUB_PAT: ${{ secrets.PAT }}
     steps:
-      - uses: actions/checkout@v2
+    - uses: actions/checkout@v2
 
-      - uses: r-lib/actions/setup-r@v2
-        with:
-          use-public-rspm: true
-          r-version: '4.0.2'
+    - uses: r-lib/actions/setup-r@v2
+      with:
+        use-public-rspm: true
+        r-version: '4.0.2'
 
-      - uses: r-lib/actions/setup-r-dependencies@v2
-        with:
-          cache: true
-          cache-version: 1
-          extra-packages: rcmdcheck
-          error-on: '"error"'
+    - uses: r-lib/actions/setup-r-dependencies@v2
+      with:
+        cache: true
+        cache-version: 1
+        extra-packages: rcmdcheck
+        error-on: '"error"'
 
-      - name: Show testthat output
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+    - name: Show testthat output
+      if: always()
+      run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+      shell: bash
 
-      - name: Upload check results
-        if: failure()
-        uses: actions/upload-artifact@main
-        with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
+    - name: Upload check results
+      if: failure()
+      uses: actions/upload-artifact@main
+      with:
+        name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+        path: check
 
     - name: manual debugging
       if: failure()
